name: 'TruffleHog'
description: 'Runs TruffleHog to uncover secrets'
# inputs:
#   severity-level:
#     description: 'Min Severity Level to Report'
#     default: "info"
#   output-filename:
#     description: 'File name containing full scan output. If unspecified, output is not saved'
runs:
  using: 'node16'
  main: 'dist/index.js'