name: 'Security Pipeline'
description: 'Run several security tools on the project'
inputs:
  severity-level:
    description: 'Min Severity Level to Report'
    required: true
  defectdojo-url:
    description: 'URL for DefectDojo Instance eg: https://defectdojo.com'
    required: true
  defectdojo-api-key:
    description: 'API key for Defect Dojo Instance'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'