name: Security Pipeline Reusable Workflow

on:
  workflow_call:
    inputs:
      continue-on-error:
        required: true
        type: boolean
        default: false
      severity-level:
        description: 'Min Severity Level to Report'
        required: true
        type: string
        default: "critical"
    secrets:
      defectdojo-url:
        description: 'URL for DefectDojo Instance eg: https://defectdojo.com'
        required: true
      defectdojo-api-key:
        description: 'API key for Defect Dojo Instance'
        required: true


jobs:
  nodejs-security-checks:
    runs-on: ubuntu-latest
    continue-on-error: ${{ inputs.continue-on-error }}
    steps:  
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Check existence of yarn.lock
        id: check_yarn_lock_file
        run: |
          if test -f "yarn.lock"; 
          then 
            echo "check_result=true" >> $GITHUB_OUTPUT
          else 
            echo "check_result=false" >> $GITHUB_OUTPUT 
          fi

      - name: Running Full Yarn Audit on Repo
        if: steps.check_yarn_lock_file.outputs.check_result == 'true'
        id: yarn_audit_full
        uses: GradiusX/security-pipeline/.github/actions/yarn_audit@dev
        with:
          output-filename: "yarn_audit.json"

      - name: Uploading Yarn Audit files to DefectDojo
        if: steps.check_yarn_lock_file.outputs.check_result == 'true'
        id: upload_defectdojo_yarn_audit
        uses: GradiusX/security-pipeline/.github/actions/upload_defectdojo@dev
        with:
          defectdojo-url: ${{ secrets.defectdojo-url }}
          defectdojo-api-key: ${{ secrets.defectdojo-api-key }}
          product-name: ${{ github.event.repository.name }}
          engagement-name: "CICD_engagement"
          scan-type: "Yarn Audit Scan"
          scan-filename: "yarn_audit.json"

      - name: Running Yarn Audit on Repo
        if: steps.check_yarn_lock_file.outputs.check_result == 'true'
        id: yarn_audit_specific
        uses: GradiusX/security-pipeline/.github/actions/yarn_audit@dev
        with:
          severity-level: ${{ inputs.severity-level }}