name: Security Pipeline Reusable Workflow

on:
  workflow_call:
    inputs:
      continue-on-error:
        required: true
        type: boolean
        default: false
      severity-level:
        description: 'Min Severity Level to Report'
        required: true
        type: string
        default: "critical"

jobs:
  security-pipeline:
    runs-on: ubuntu-latest
    continue-on-error: ${{ inputs.continue-on-error }}
    steps:  
      # - name: Check out repository code
      #   uses: actions/checkout@v3
      # - name: Running Yarn Audit on Repo - direct
      #   id: yarn_audit_direct
      #   run: |
      #     yarn audit --level ${{ inputs.severity-level }}

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Check existance of yarn.lock
        id: check_yarn_lock
        run: |
          if test -f "yarn.lock"; then return 0; else return 1; fi

      - name: Running Yarn Audit on Repo - indirect
        id: yarn_audit_indirect
        if: steps.check_yarn_lock.outputs == 0
        uses: GradiusX/security-pipeline/.github/actions/yarn_audit@main
        with:
          severity-level: ${{ inputs.severity-level }}