name: Security Pipeline Reusable Workflow

on:
  workflow_call:
    inputs:
      continue-on-error:
        required: true
        type: boolean
        default: false
      severity-level:
        required: true
        type: string
        default: "critical"

jobs:
  security-pipeline:
    runs-on: ubuntu-latest
    continue-on-error: ${{ inputs.continue-on-error }}
    steps:  
      # - name: Check out repository code
      #   uses: actions/checkout@v3
      # - name: Running Yarn Audit on Repo - direct
      #   id: yarn_audit_direct
      #   run: |
      #     yarn audit --level ${{ inputs.severity-level }}

      - name: Check out repository code
        uses: actions/checkout@v3
        # with:
        #   path: app
      - name: Running Yarn Audit on Repo - indirect
        id: yarn_audit_indirect
        uses: GradiusX/security-pipeline/.github/actions/yarn@main
        with:
          severity-level: ${{ inputs.severity-level }}
      # Tutorial for calling workflow actions: https://stackoverflow.com/questions/71046096/reusable-workflows-with-local-actions